### ISSUE TITLE
error when attempting to install on osx

### ISSUE THREAD

**Issue by joeferraro** [LinusU/fs-xattr#8]
```
npm install fs-xattr
-
> fs-xattr@0.1.6 install /Users/josephferraro/Desktop/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/xattr.o
In file included from ../src/xattr.cc:21:
../src/error.cc:109:3: error: call to 'NanThrowError' is ambiguous
  NanThrowError(err);
  ^~~~~~~~~~~~~
../node_modules/nan/nan.h:711:3: note: candidate function
  X(Error)
  ^
../node_modules/nan/nan.h:705:21: note: expanded from macro 'X'
    NAN_INLINE void NanThrow ## NAME(v8::Handle<v8::String> errmsg) {          \
                    ^
<scratch space>:91:1: note: expanded from here
NanThrowError
^
../node_modules/nan/nan.h:719:19: note: candidate function
  NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
                  ^
1 error generated.
make: *** [Release/obj.target/xattr/src/xattr.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/josephferraro/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/josephferraro/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/josephferraro/Desktop/node_modules/fs-xattr
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/josephferraro/.nvm/versions/node/v0.12.7/bin/node" "/Users/josephferraro/.nvm/versions/node/v0.12.7/bin/npm" "install" "fs-xattr"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fs-xattr@0.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-xattr@0.1.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/josephferraro/Desktop/npm-debug.log
```

**Comment by joeferraro** [comment]
fyi, this is likely a result of `nan`'s recent update: https://github.com/nodejs/nan/issues/387

**Comment by smith-kyle** [comment]
Made a pull request to fix this #9

**Comment by joeferraro** [comment]
@smith-kyle :+1:

**Comment by mpderbec** [comment]
:+1:

**Comment by Ivshti** [comment]
:+1: 
Just encountered this issue

**Comment by LinusU** [comment]
Fixed with `0.1.7`

**Comment by maxkorp** [comment]
Still broken, but with a different error
```
../src/xattr.cc:40:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
../src/xattr.cc:53:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
../src/xattr.cc:85:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
../src/xattr.cc:107:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
../src/xattr.cc:120:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
../src/xattr.cc:157:25: error: use of undeclared identifier 'errno'
    ThrowExceptionErrno(errno);
                        ^
6 errors generated.
make: *** [Release/obj.target/xattr/src/xattr.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/maxk/.nvm/v0.10.39/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/Users/maxk/.nvm/v0.10.39/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/maxk/Development/gitkraken/build/node_modules/grunt-appdmg/node_modules/appdmg/node_modules/fs-xattr
```
CDed in to confirm it wasnt just caching an old version, its latest.

**Comment by LinusU** [comment]
That's strange... I don't get that error. Which platform are you on?

Could you try to add `#include <errno.h>` in the top of `xattr.cc`?

**Comment by LinusU** [comment]
@maxkorp should be fixed with `0.1.8` :+1:

**Comment by maxkorp** [comment]
Whoops, sorry I didn't see that. Latest OSX, but thanks man!

**Comment by LinusU** [comment]
No problem :+1:
